DELETE FROM user_cards_stack WHERE TRUE;
DELETE FROM user_cards_deck WHERE TRUE;
DELETE FROM pack_cards WHERE TRUE;
DELETE FROM trade_offers WHERE TRUE;
DELETE FROM shop_cards WHERE TRUE;
DELETE FROM packs WHERE TRUE;
DELETE FROM cards WHERE TRUE;
DELETE FROM users WHERE TRUE;
