CREATE TABLE "users" (
                         "username" varchar(50) PRIMARY KEY,
                         "password_hash" text NOT NULL,
                         "name" varchar(50) NOT NULL,
                         "elo" int NOT NULL,
                         "coins" int NOT NULL,
                         "wins" int NOT NULL DEFAULT 0,
                         "losses" int NOT NULL DEFAULT 0,
                         "bio" varchar(200) DEFAULT NULL,
                         "image" varchar(200) DEFAULT NULL
);

CREATE TABLE "user_cards_stack" (
                                    "username" varchar(50) NOT NULL,
                                    "card_id" text NOT NULL,
                                    PRIMARY KEY ("username", "card_id")
);

CREATE TABLE "user_cards_deck" (
                                   "username" varchar(50) NOT NULL,
                                   "card_id" text NOT NULL,
                                   PRIMARY KEY ("username", "card_id")
);

CREATE TABLE "trade_offers" (
                                "id" text PRIMARY KEY,
                                "username" varchar(50) NOT NULL,
                                "card_id" text NOT NULL,
                                "type" int NOT NULL,
                                "min_damage" float NOT NULL
);

CREATE TABLE "cards" (
                         "id" text PRIMARY KEY,
                         "name" text NOT NULL,
                         "type" int NOT NULL,
                         "element" int NOT NULL,
                         "damage" float NOT NULL
);

CREATE TABLE "packs" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE "pack_cards" (
                              "pack_id" int NOT NULL,
                              "card_id" text NOT NULL,
                              PRIMARY KEY ("pack_id", "card_id")
);

CREATE TABLE "shop_cards" (
                              "card_id" text PRIMARY KEY NOT NULL,
                              "price" int NOT NULL
);

ALTER TABLE "user_cards_stack" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "user_cards_stack" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "user_cards_deck" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "user_cards_deck" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "trade_offers" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "trade_offers" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "pack_cards" ADD FOREIGN KEY ("pack_id") REFERENCES "packs" ("id");

ALTER TABLE "pack_cards" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "shop_cards" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");
